<?php echo $this->tag->stylesheetLink('css/bootstrap.min.css'); ?>
<?php echo $this->tag->stylesheetLink('css/bootstrap-datetimepicker.min.css'); ?>
<?php echo $this->tag->stylesheetLink('css/bootstrap-select.min.css'); ?>
<?php echo $this->tag->stylesheetLink('css/font-awesome.min.css'); ?>
<?php echo $this->tag->stylesheetLink('css/AdminLTE.min.css'); ?>
<?php echo $this->tag->stylesheetLink('plugins/iCheck/minimal/blue.css'); ?>
<?php echo $this->tag->stylesheetLink('plugins/jquery-treeview/jquery.treeview.css'); ?>
<?php echo $this->tag->stylesheetLink('css/include-after.css'); ?>
<?php echo $this->tag->stylesheetLink('plugins/datatable/datatables.min.css'); ?>
<?php echo $this->tag->stylesheetLink('css/custom.css'); ?>
