<?php echo $this->tag->javascriptInclude('js/jquery-2.2.4.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/jquery-migrate-1.4.1.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/jquery-ui-1.12.1.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/jquery.ui.touch-punch.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/jquery.slimscroll.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/cookie.js'); ?>
<?php echo $this->tag->javascriptInclude('js/moment.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/moment/ja.js'); ?>
<?php echo $this->tag->javascriptInclude('plugins/jquery-treeview/jquery.treeview.js'); ?>
<?php echo $this->tag->javascriptInclude('plugins/iCheck/icheck.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/bootstrap.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/bootstrap-select.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/bootstrap-datetimepicker.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/application.js'); ?>
<?php echo $this->tag->javascriptInclude('plugins/datatable/datatables.min.js'); ?>
<?php echo $this->tag->javascriptInclude('plugins/jqx/jqx-all.js'); ?>
<?php echo $this->tag->javascriptInclude('js/Chart.min.js'); ?>
<?php echo $this->tag->javascriptInclude('js/palette.js'); ?>
<?php echo $this->tag->javascriptInclude('js/html2canvas.js'); ?>
<?php echo $this->tag->javascriptInclude('js/readmore.min.js'); ?>
